# Linear algebra
### Following the 3Blue1Brown Essence of Linear Algebra Course

* [Video Playlist](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

## Chapter One: Vectors

### How to create a numpy array

In [2]:

import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

### Operations: addition

In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Function syntax
np.add(a, b)

# Operator syntax
a + b

array([5, 7, 9])

### Operators: multiplication

In [11]:
import numpy as np
a = np.array([1, 2, 3])
b = 4

# Function syntax
np.multiply(a, b)

# Operator syntax
a * b

array([ 4,  8, 12])

## Chapter 2: Spans
Not really anything to cover here programming wise, it was mostly new core concepts:

* Linear Combination: An expression formed by multiplying vectors by scalars and adding the results. For example, given vectors v and w, any vector of the form a·v + b·w (where a and b are scalars) is a linear combination of v and w.

* Span: The set of all possible linear combinations of a given set of vectors. For instance, the span of vectors v and w includes all vectors that can be expressed as a·v + b·w for all real numbers a and b.

* Basis Vectors: A set of linearly independent vectors that span a vector space. In two-dimensional space, the standard basis vectors are typically denoted as î and ĵ, corresponding to the unit vectors along the x-axis and y-axis, respectively.
3blue1brown.com

* Linear Dependence: A situation where at least one vector in a set can be expressed as a linear combination of the others. This implies redundancy in the set, as some vectors do not add new directions to the span.
3blue1brown.com

* Linear Independence: A condition where no vector in a set can be written as a linear combination of the others. This ensures that each vector adds a new dimension to the span, making the set a suitable basis for the space.


# Chapter 3: Linear Transformations and Matrices

### Initializing 2x2 matrices

So in numpy, arrays matrices are described in row-major order (also called C-order), meaning the first index refers to the row and the second index refers to the column. When you create or view a 2D array in NumPy, each inner sequence corresponds to a row, and each element within that sequence corresponds to a column entry.

So if you've got a 2x2 matrix, you need to enter it ROW first, not column-first.


In [28]:
import numpy as np

# 2x2 Transformation matrix (columns are i-hat and j-hat)
# 
#    3  2  
#   -2  1  
# 
# Which you could read as:
#
#   i-hat is x=3, y=-2
#   j-hat is x=2, y=1
#
# Both the x's go first in numpy, then the y's
#
#   np.array([[ix, jx], [iy, jy]])
#

np.array([[3, 2], [-2, 1]])

array([[ 3,  2],
       [-2,  1]])

### Matrix vector multiplication

In [6]:
import numpy as np

# Any Old Vector
# Note: this might not be right. Maybe it should be np.array([[5],[7]])?
v = np.array([5, 7])

# 2x2 Transformation matrix (columns are i-hat and j-hat)
#   i-hat is [3, -2]
#   j-hat is [2, 1]

t = np.array([[3, 2],
              [-2, 1]])

# Shorthand operator
t @ v

# Alternate syntax
np.dot(t, v)

array([ 1, 17])

# Chapter 4: Matrix multiplication as composition

In [22]:
import numpy as np

shear_matrix = np.array([[1, 1],
                         [0, 1]])
rotation_matrix = np.array([[0, -1],
                            [1, 0]])

# Note that the order the matrices are multiplied is important.
# Matrix multiplication is not commutative.

print(rotation_matrix @ shear_matrix)
print(shear_matrix @ rotation_matrix)

# Let's say we have a couple transformations we want to apply
# to a vector.
#
#     [1 1]          [0 -1]          [5]
#     [0 1]          [1  0]          [7]
# shear_matrix   rotation_matrix      v
#

v = np.array([[5], [7]])

print(shear_matrix @ rotation_matrix @ v)

# Equivalent to:
# np.dot(np.dot(shear_matrix, rotation_matrix), v)


[[ 0 -1]
 [ 1  1]]
[[ 1 -1]
 [ 1  0]]
[[-2]
 [ 5]]


# Chapter 5: Three-dimensional Linear Transformations

In [23]:
import numpy as np

second_transformation = np.array([[0, -2, 2],
                                  [5, 1, 5],
                                  [1, 4, -1]])

first_transformation = np.array([[0, 1, 2],
                                 [3, 4, 5],
                                 [6, 7, 8]])

print(second_transformation @ first_transformation)


[[ 6  6  6]
 [33 44 55]
 [ 6 10 14]]
