# Linear algebra
### Following the 3Blue1Brown Essence of Linear Algebra Course

* [Video Playlist](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

## Chapter One: Vectors

### How to create a numpy array

In [2]:

import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

### Operations: addition

In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Function syntax
np.add(a, b)

# Operator syntax
a + b

array([5, 7, 9])

### Operators: multiplication

In [11]:
import numpy as np
a = np.array([1, 2, 3])
b = 4

# Function syntax
np.multiply(a, b)

# Operator syntax
a * b

array([ 4,  8, 12])