# Linear algebra
### Following the 3Blue1Brown Essence of Linear Algebra Course

* [Video Playlist](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

## Chapter One: Vectors

### How to create a numpy array

In [1]:

import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

### Operations: addition

In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Function syntax
np.add(a, b)

# Operator syntax
a + b

array([5, 7, 9])

### Operators: multiplication

In [11]:
import numpy as np
a = np.array([1, 2, 3])
b = 4

# Function syntax
np.multiply(a, b)

# Operator syntax
a * b

array([ 4,  8, 12])

## Chapter 2: Spans
Not really anything to cover here programming wise, it was mostly new core concepts:

* Linear Combination: An expression formed by multiplying vectors by scalars and adding the results. For example, given vectors v and w, any vector of the form a·v + b·w (where a and b are scalars) is a linear combination of v and w.

* Span: The set of all possible linear combinations of a given set of vectors. For instance, the span of vectors v and w includes all vectors that can be expressed as a·v + b·w for all real numbers a and b.

* Basis Vectors: A set of linearly independent vectors that span a vector space. In two-dimensional space, the standard basis vectors are typically denoted as î and ĵ, corresponding to the unit vectors along the x-axis and y-axis, respectively.
3blue1brown.com

* Linear Dependence: A situation where at least one vector in a set can be expressed as a linear combination of the others. This implies redundancy in the set, as some vectors do not add new directions to the span.
3blue1brown.com

* Linear Independence: A condition where no vector in a set can be written as a linear combination of the others. This ensures that each vector adds a new dimension to the span, making the set a suitable basis for the space.


# Chapter 3: Linear Transformations and Matrices

### Initializing 2x2 matrices

So in numpy, arrays matrices are described in row-major order (also called C-order), meaning the first index refers to the row and the second index refers to the column. When you create or view a 2D array in NumPy, each inner sequence corresponds to a row, and each element within that sequence corresponds to a column entry.

So if you've got a 2x2 matrix, you need to enter it ROW first, not column-first.


In [28]:
import numpy as np

# 2x2 Transformation matrix (columns are i-hat and j-hat)
# 
#    3  2  
#   -2  1  
# 
# Which you could read as:
#
#   i-hat is x=3, y=-2
#   j-hat is x=2, y=1
#
# Both the x's go first in numpy, then the y's
#
#   np.array([[ix, jx], [iy, jy]])
#

np.array([[3, 2], [-2, 1]])

array([[ 3,  2],
       [-2,  1]])

### Matrix vector multiplication

In [6]:
import numpy as np

# Any Old Vector
# Note: this might not be right. Maybe it should be np.array([[5],[7]])?
v = np.array([5, 7])

# 2x2 Transformation matrix (columns are i-hat and j-hat)
#   i-hat is [3, -2]
#   j-hat is [2, 1]

t = np.array([[3, 2],
              [-2, 1]])

# Shorthand operator
t @ v

# Alternate syntax
np.dot(t, v)

array([ 1, 17])

# Chapter 4: Matrix multiplication as composition

In [22]:
import numpy as np

shear_matrix = np.array([[1, 1],
                         [0, 1]])
rotation_matrix = np.array([[0, -1],
                            [1, 0]])

# Note that the order the matrices are multiplied is important.
# Matrix multiplication is not commutative.

print(rotation_matrix @ shear_matrix)
print(shear_matrix @ rotation_matrix)

# Let's say we have a couple transformations we want to apply
# to a vector.
#
#     [1 1]          [0 -1]          [5]
#     [0 1]          [1  0]          [7]
# shear_matrix   rotation_matrix      v
#

v = np.array([[5], [7]])

print(shear_matrix @ rotation_matrix @ v)

# Equivalent to:
# np.dot(np.dot(shear_matrix, rotation_matrix), v)


[[ 0 -1]
 [ 1  1]]
[[ 1 -1]
 [ 1  0]]
[[-2]
 [ 5]]


# Chapter 5: Three-dimensional Linear Transformations

In [23]:
import numpy as np

second_transformation = np.array([[0, -2, 2],
                                  [5, 1, 5],
                                  [1, 4, -1]])

first_transformation = np.array([[0, 1, 2],
                                 [3, 4, 5],
                                 [6, 7, 8]])

print(second_transformation @ first_transformation)


[[ 6  6  6]
 [33 44 55]
 [ 6 10 14]]


# Chapter 6: Determinants

Some linear transformations stretch space out and other squish space in. One thing that's useful for understanding these linear transformations is to measure exactly how much it stretches or squishes things.

More specifically, to measure the factor of the area of a given region increases or decreases.

This scaling factor by which a linear transformation changes any area is called the **determinant** of the transformation.

Key things indicated by determinant values:

* Values greater than 1.0 are scaling upwards
* Values of 1.0 are isometry unity, no area change.
* Values of greater than 0 but less than 1 means it contracts
* Values of 0 means that the transformation collapses the space into a lower dimension, at least one vector has become linearly dependent, or the transformation maps some non-zero vectors to zero.
* Values in the negatives mean all the above, but also that it has also reversed orientation.


In [25]:
import numpy as np

matrix = np.array([[3, 0],
                   [0, 2]])
np.linalg.det(matrix)


np.float64(6.0)

# Chapter 7: Inverse matrices, column space and null space

In [34]:
import numpy as np

# Let's say you have equations:
#  2x + 2y = -4
#  1x + 3y = -1

# We can represent this as a matrix equation:
#  [2 2] [x] = [-4]
#  [1 3] [y]   [-1]

# We can solve this by finding the inverse of the matrix
# and multiplying it by the constant vector.

matrix = np.array([[2, 2],
                   [1, 3]])

constant_vector = np.array([[-4], [-1]])

# inverse of matrix
inverse_matrix = np.linalg.inv(matrix)
print(f"inverse_matrix\n{inverse_matrix}")

# multiply inverse matrix by constant vector to get x_vector
x_vector = inverse_matrix @ constant_vector
print(f"\nx_vector\n{x_vector}")

# Let's check our work
matrix @ x_vector == constant_vector


inverse_matrix
[[ 0.75 -0.5 ]
 [-0.25  0.5 ]]

x_vector
[[-2.5]
 [ 0.5]]


array([[ True],
       [ True]])

In [36]:
# Also works in higher dimensions
import numpy as np

matrix = np.array([[2, 5, 3],
                   [4, 0, 8],
                   [1, 3, 0]])

inverse_matrix = np.linalg.inv(matrix)

constant_vector = np.array([[-3],
                            [0],
                            [2]])

x_vector = inverse_matrix @ constant_vector
print(f"x_vector\n{x_vector}\n")

# Let's check our work
matrix @ x_vector == constant_vector





x_vector
[[ 5.42857143]
 [-1.14285714]
 [-2.71428571]]



array([[ True],
       [ True],
       [ True]])

In [43]:
import numpy as np

matrix = np.array([[1, 0],
                   [0, 1]])
rank = np.linalg.matrix_rank(matrix)
print(f"matrix\n{matrix}\nrank: {rank}\n")

collapsed_matrix = np.array([[1, 0],
                             [0, 0]])
rank = np.linalg.matrix_rank(collapsed_matrix)
print(f"collapsed_matrix\n{collapsed_matrix}\nrank: {rank}\n")

linearly_dependent_matrix = np.array([[1, 2],
                                      [0, 0]])
rank = np.linalg.matrix_rank(linearly_dependent_matrix)
print(f"linearly_dependent_matrix\n{linearly_dependent_matrix}\nrank: {rank}\n")

zero_point_matrix = np.array([[0, 0],
                              [0, 0]])
rank = np.linalg.matrix_rank(zero_point_matrix)
print(f"zero_point_matrix\n{zero_point_matrix}\nrank: {rank}\n")



matrix
[[1 0]
 [0 1]]
rank: 2

collapsed_matrix
[[1 0]
 [0 0]]
rank: 1

linearly_dependent_matrix
[[1 2]
 [0 0]]
rank: 1

zero_point_matrix
[[0 0]
 [0 0]]
rank: 0



# Chapter 8: Non-square Matrices
It's totally possible to have a transformation that goes from a 2d space to a 3d space, 3d to 1d space, etc.

In [2]:
import numpy as np

input = np.array([[2],
                  [7]])
transformation_matrix = np.array([[2, 2],
                                  [-1, 1],
                                  [-2, 1]])
transformation_matrix @ input


array([[18],
       [ 5],
       [ 3]])

# Chapter 9: Dot products and duality

In [54]:
import numpy as np

a = np.array([2, 7, 1])
b = np.array([8, 2, 8])

# you can also use the shorthand operator here: a @ b
print(a.dot(b))

# tip the vector b on its side to become a matrix
# you could also do: m = b.reshape(1, -1)
m = np.array([[8, 2, 8]])

print(m.dot(a))

38
38
[38]


# Chapter 10 & 11: cross products

In [6]:
import numpy as np

# 3d cross product
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
cross_product = np.cross(vector_a, vector_b)
print(cross_product)  # Output: [-3  6 -3]

# 2d cross product
def cross2d(x, y):
    return x[0] * y[1] - x[1] * y[0]
a = np.array([2, 4])
b = np.array([1, 5])
print(cross2d(a, b)) # Output: 6

# Note: you can do this, but it'll throw a deprecation warning: result = np.cross(a, b)

# In the 2d case, the cross product is the same as the determinant of the matrix formed by the two vectors
det_result = np.linalg.det(np.array([[a[0], b[0]],
                                     [a[1], b[1]]]))
print(det_result) # Output: 6



[-3  6 -3]
6
6.0


# Chapter 12 - Was about Cramer's rule expressed geometrically
Honestly I skimmed it and then watched a different video on how to compute it. The geometric explanation was not landing for me.

# Chapter 13 - Changes of Basis

In [10]:
import numpy as np

v_in_jens_system = np.array([[-1],[2]])
change_of_basis_matrix = np.array([[2, -1], 
                                   [1, 1]])

print("v in jen's system in our system:")
print(change_of_basis_matrix @ v_in_jens_system)

rotation_matrix_in_our_system = np.array([[0, -1], 
                                          [1, 0]])
print("rotated @ translated vector in our system:")
print(rotation_matrix_in_our_system @ change_of_basis_matrix @ v_in_jens_system)

print("rotated @ translated vector back in her system:")
print(np.linalg.inv(change_of_basis_matrix) @ rotation_matrix_in_our_system @ change_of_basis_matrix @ v_in_jens_system)

print("rotated @ translated vector back in our system again (for funsies):")
print(change_of_basis_matrix @ np.linalg.inv(change_of_basis_matrix) @ rotation_matrix_in_our_system @ change_of_basis_matrix @ v_in_jens_system)


v in jen's system in our system:
[[-4]
 [ 1]]
rotated @ translated vector in our system:
[[-1]
 [-4]]
rotated @ translated vector back in her system:
[[-1.66666667]
 [-2.33333333]]
rotated @ translated vector back in our system:
[[-1.]
 [-4.]]


# Chapter 14 Eigenvectors and Eigenvalues

In [2]:
import numpy as np

A = np.array([[0, 2],
              [2, 3]])  # 2x2 matrix

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[-1.  4.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


# Bonus: How to calculate SVD

In [3]:
import numpy as np

# Define your matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# Compute the SVD
U, S, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Singular values:", S)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
Singular values: [9.508032   0.77286964]
V^T matrix:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
